config/routes.rb
DemoApp::Application.routes.draw do
  resources :microposts

  resources :tooths

  resources :foots

  resources :children

  resources :people

  resources :dwarves

  resources :users

end

app/models/foot.rb
class Foot < ActiveRecord::Base
end

app/controllers/foots_controller.rb
class FootsController < ApplicationController
  # GET /foots
  # GET /foots.json
  def index
    @foots = Foot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foots }
    end
  end

  # GET /foots/1
  # GET /foots/1.json
  def show
    @foot = Foot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foot }
    end
  end

  # GET /foots/new
  # GET /foots/new.json
  def new
    @foot = Foot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foot }
    end
  end

  # GET /foots/1/edit
  def edit
    @foot = Foot.find(params[:id])
  end

  # POST /foots
  # POST /foots.json
  def create
    @foot = Foot.new(params[:foot])

    respond_to do |format|
      if @foot.save
        format.html { redirect_to @foot, notice: 'Foot was successfully created.' }
        format.json { render json: @foot, status: :created, location: @foot }
      else
        format.html { render action: "new" }
        format.json { render json: @foot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foots/1
  # PUT /foots/1.json
  def update
    @foot = Foot.find(params[:id])

    respond_to do |format|
      if @foot.update_attributes(params[:foot])
        format.html { redirect_to @foot, notice: 'Foot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @foot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foots/1
  # DELETE /foots/1.json
  def destroy
    @foot = Foot.find(params[:id])
    @foot.destroy

    respond_to do |format|
      format.html { redirect_to foots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/foots_helper.rb
module FootsHelper
end

app/views/foots/_form.html.erb
<%= form_for(@foot) do |f| %>
  <% if @foot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foot.errors.count, "error") %> prohibited this foot from being saved:</h2>

      <ul>
      <% @foot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Foot %><br />
    <%= f.text_field :Foot %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foots/edit.html.erb
<h1>Editing foot</h1>

<%= render 'form' %>

<%= link_to 'Show', @foot %> |
<%= link_to 'Back', foots_path %>

app/views/foots/index.html.erb
<h1>Listing foots</h1>

<table>
  <tr>
    <th>Foot</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @foots.each do |foot| %>
  <tr>
    <td><%= foot.Foot %></td>
    <td><%= foot.name %></td>
    <td><%= foot.email %></td>
    <td><%= link_to 'Show', foot %></td>
    <td><%= link_to 'Edit', edit_foot_path(foot) %></td>
    <td><%= link_to 'Destroy', foot, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Foot', new_foot_path %>

app/views/foots/new.html.erb
<h1>New foot</h1>

<%= render 'form' %>

<%= link_to 'Back', foots_path %>

app/views/foots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Foot:</b>
  <%= @foot.Foot %>
</p>

<p>
  <b>Name:</b>
  <%= @foot.name %>
</p>

<p>
  <b>Email:</b>
  <%= @foot.email %>
</p>


<%= link_to 'Edit', edit_foot_path(@foot) %> |
<%= link_to 'Back', foots_path %>